name: 'Steve Testa'
description: ''
author: 'Steve Testa'
inputs:
  nupkgPath: 
    required: true
    description: 'path to the nupkg'
  nuspecName:
    required: true
    description: ''
  version: 
    required: false
    description: 'NuGet Package Version'
    default: '0.1.0'
  repositoryUrl:
    required: false
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
