name: 'Edit NuGet Package Manifest'
description: 'Updates the manifest metadata inside an existing nuget package.'
author: 'Steve Testa'
inputs:
  nupkgPath: 
    required: true
    description: 'path to the nupkg'
  nuspecPath:
    required: false
    description: 'an external nuspec file whose content will be used as the base manifest'
  id: 
    required: false
    description: ''
  title: 
    required: false
    description: ''
  version: 
    required: false
    description: 'NuGet Package Version'
    default: '0.1.0'
  authors: 
    required: false
    description: ''
  owners: 
    required: false
    description: ''
  repositoryUrl:
    required: false
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
