name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  nupkg-path: 
    required: true
    description: 'path to the nupkg'
  version: 
    required: true
    description: 'NuGet Package Version'
    default: '0.1.0'
runs:
  using: 'node12'
  main: 'dist/index.js'
